export const keywords = [
  "CPU",
  "GPU",
  "Memory",
  "Motherboard",
  "PSU",
  "PC Case",
  "Storage",
  "Configuration",
];

export const keywordsAdmin = [
  "Users",
  "CPU",
  "GPU",
  "Memory",
  "Motherboard",
  "PSU",
  "PC Case",
  "Storage",
  "Configuration",
];

export const fields = {
  CPU: [
    "Brand",
    "Model",
    "Cores",
    "Frequency",
    "Integrated Graphics",
    "Price",
    "Quantity",
  ],
  GPU: ["Brand", "Model", "VRam", "Frequency", "Price", "Quantity"],
  Memory: ["Brand", "Model", "Type", "Size", "Frequency", "Price", "Quantity"],
  Motherboard: ["Brand", "Model", "Form Factor", "Socket", "Price", "Quantity"],
  PSU: [
    "Brand",
    "Model",
    "Form Factor",
    "Wattage",
    "Efficiency",
    "Price",
    "Quantity",
  ],
  "PC Case": ["Brand", "Model", "Form Factor", "Price", "Quantity"],
  Storage: ["Brand", "Model", "Capacity", "Type", "Price", "Quantity"],
  Configuration: [
    "Date Created",
    "CPU",
    "GPU",
    "Memory",
    "Motherboard",
    "Storage",
    "PSU",
    "PC Case",
  ],
};

export const fieldsAdmin = {
  Users: ["Username", "Email", "Role"],
  CPU: [
    "Brand",
    "Model",
    "Cores",
    "Frequency",
    "Integrated Graphics",
    "Price",
    "Quantity",
  ],
  GPU: ["Brand", "Model", "VRam", "Frequency", "Price", "Quantity"],
  Memory: ["Brand", "Model", "Type", "Size", "Frequency", "Price", "Quantity"],
  Motherboard: ["Brand", "Model", "Form Factor", "Socket", "Price", "Quantity"],
  PSU: [
    "Brand",
    "Model",
    "Form Factor",
    "Wattage",
    "Efficiency",
    "Price",
    "Quantity",
  ],
  "PC Case": ["Brand", "Model", "Form Factor", "Price", "Quantity"],
  Storage: ["Brand", "Model", "Capacity", "Type", "Price", "Quantity"],
  Configuration: [
    "Date Created",
    "CPU",
    "GPU",
    "Memory",
    "Motherboard",
    "Storage",
    "PSU",
    "PC Case",
  ],
};
